# Generated by Django 4.0.5 on 2022-07-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_restaurant', '0002_mancare_link_poza_mancare_nume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mancare',
            name='link_poza',
            field=models.CharField(default='Doamne ajuta', max_length=200),
        ),
    ]
